import 'package:smartpay/models/country_code.dart';

class CountryRepository {
  List<Map<String, dynamic>> getAll() => _countryCodes;

  List<CountryCode> getCountryCode() =>
      _countryCodes.map((map) => CountryCode.fromJson(map)).toList();

  final List<Map<String, dynamic>> _countryCodes = [
    {
      "name": "Afghanistan",
      "flag": "🇦🇫",
      "code": "AF",
      "dial_code": "+93",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "AFN",
      "currency_name": "Afghan afghani",
      "symbol": "؋",
    },
    {
      "name": "Åland Islands",
      "flag": "🇦🇽",
      "code": "AX",
      "dial_code": "+358",
      "min_length": 15,
      "max_length": 15,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Albania",
      "flag": "🇦🇱",
      "code": "AL",
      "dial_code": "+355",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "ALL",
      "currency_name": "Albanian lek",
      "symbol": "Lek",
    },
    {
      "name": "Algeria",
      "flag": "🇩🇿",
      "code": "DZ",
      "dial_code": "+213",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "DZD",
      "currency_name": "Algerian dinar",
      "symbol": "دج",
    },
    {
      "name": "American Samoa",
      "flag": "🇦🇸",
      "code": "AS",
      "dial_code": "+1684",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "USD",
      "currency_name": "United State Dollar",
      "symbol": "\$",
    },
    {
      "name": "Andorra",
      "flag": "🇦🇩",
      "code": "AD",
      "dial_code": "+376",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Angola",
      "flag": "🇦🇴",
      "code": "AO",
      "dial_code": "+244",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "AOA",
      "currency_name": "Angolan kwanza",
      "symbol": "Kz",
    },
    {
      "name": "Anguilla",
      "flag": "🇦🇮",
      "code": "AI",
      "dial_code": "+1264",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "XCD",
      "currency_name": "East Caribbean dollar",
      "symbol": "\$",
    },
    {
      "name": "Antarctica",
      "flag": "🇦🇶",
      "code": "AQ",
      "dial_code": "+672",
      "min_length": 6,
      "max_length": 6,
      "currency_code": "AUD",
      "currency_name": "Australian dollar",
      "symbol": "A\$",
    },
    {
      "name": "Antigua and Barbuda",
      "flag": "🇦🇬",
      "code": "AG",
      "dial_code": "+1268",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "XCD",
      "currency_name": "East Caribbean dollar",
      "symbol": "\$",
    },
    {
      "name": "Argentina",
      "flag": "🇦🇷",
      "code": "AR",
      "dial_code": "+54",
      "min_length": 12,
      "max_length": 12,
      "currency_code": "ARS",
      "currency_name": "Argentine peso",
      "symbol": "\$",
    },
    {
      "name": "Armenia",
      "flag": "🇦🇲",
      "code": "AM",
      "dial_code": "+374",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "AMD",
      "currency_name": "Armenian dram",
      "symbol": "֏",
    },
    {
      "name": "Aruba",
      "flag": "🇦🇼",
      "code": "AW",
      "dial_code": "+297",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "AWG",
      "currency_name": "Aruban florin",
      "symbol": "ƒ"
    },
    {
      "name": "Australia",
      "flag": "🇦🇺",
      "code": "AU",
      "dial_code": "+61",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "AUD",
      "currency_name": "Australian dollar",
      "symbol": "A\$",
    },
    {
      "name": "Austria",
      "flag": "🇦🇹",
      "code": "AT",
      "dial_code": "+43",
      "min_length": 13,
      "max_length": 13,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Azerbaijan",
      "flag": "🇦🇿",
      "code": "AZ",
      "dial_code": "+994",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "AZN",
      "currency_name": "Azerbaijani manat",
      "symbol": "₼",
    },
    {
      "name": "Bahamas",
      "flag": "🇧🇸",
      "code": "BS",
      "dial_code": "+1242",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "BSD",
      "currency_name": "Bahamian dollar",
      "symbol": "\$",
    },
    {
      "name": "Bahrain",
      "flag": "🇧🇭",
      "code": "BH",
      "dial_code": "+973",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "BHD",
      "currency_name": "Bahraini dinar",
      "symbol": "BD",
    },
    {
      "name": "Bangladesh",
      "flag": "🇧🇩",
      "code": "BD",
      "dial_code": "+880",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "BDT",
      "currency_name": "Bangladeshi taka",
      "symbol": " Tk",
    },
    {
      "name": "Barbados",
      "flag": "🇧🇧",
      "code": "BB",
      "dial_code": "+1246",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "BBD",
      "currency_name": "Barbadian dollar",
      "symbol": "\$",
    },
    {
      "name": "Belarus",
      "flag": "🇧🇾",
      "code": "BY",
      "dial_code": "+375",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "BYN",
      "currency_name": "New Belarusian ruble",
      "symbol": "Br",
    },
    {
      "name": "Belgium",
      "flag": "🇧🇪",
      "code": "BE",
      "dial_code": "+32",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Belize",
      "flag": "🇧🇿",
      "code": "BZ",
      "dial_code": "+501",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "BZD",
      "currency_name": "Belize dollar",
      "symbol": "BZ\$",
    },
    {
      "name": "Benin",
      "flag": "🇧🇯",
      "code": "BJ",
      "dial_code": "+229",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "XOF",
      "currency_name": "West African CFA franc",
      "symbol": "CFA",
    },
    {
      "name": "Bermuda",
      "flag": "🇧🇲",
      "code": "BM",
      "dial_code": "+1441",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "BMD",
      "currency_name": "Bermudian dollar",
      "symbol": "\$",
    },
    {
      "name": "Bhutan",
      "flag": "🇧🇹",
      "code": "BT",
      "dial_code": "+975",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "BTN",
      "currency_name": "Bhutanese ngultrum",
      "symbol": "Nu.",
    },
    {
      "name": "Bolivia, Plurinational State of bolivia",
      "flag": "🇧🇴",
      "code": "BO",
      "dial_code": "+591",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "BOB",
      "currency_name": "Bolivian boliviano",
      "symbol": "\$b",
    },
    {
      "name": "Bosnia and Herzegovina",
      "flag": "🇧🇦",
      "code": "BA",
      "dial_code": "+387",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "BAM",
      "currency_name": "Bosnia and Herzegovina convertible mark",
      "symbol": "KM",
    },
    {
      "name": "Botswana",
      "flag": "🇧🇼",
      "code": "BW",
      "dial_code": "+267",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "BWP",
      "currency_name": "Botswana pula",
      "symbol": "P",
    },
    {
      "name": "Bouvet Island",
      "flag": "🇧🇻",
      "code": "BV",
      "dial_code": "+47",
      "min_length": 15,
      "max_length": 15,
      "currency_code": "NOK",
      "currency_name": "Norwegian krone",
      "symbol": "kr",
    },
    {
      "name": "Brazil",
      "flag": "🇧🇷",
      "code": "BR",
      "dial_code": "+55",
      "min_length": 11,
      "max_length": 11,
      "currency_code": "BRL",
      "currency_name": "Brazilian real",
      "symbol": "R\$",
    },
    {
      "name": "British Indian Ocean Territory",
      "flag": "🇮🇴",
      "code": "IO",
      "dial_code": "+246",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "USD",
      "currency_name": "United States dollar",
      "symbol": "\$",
    },
    {
      "name": "Brunei Darussalam",
      "flag": "🇧🇳",
      "code": "BN",
      "dial_code": "+673",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "BND",
      "currency_name": "Brunei dollar",
      "symbol": "\$",
    },
    {
      "name": "Bulgaria",
      "flag": "🇧🇬",
      "code": "BG",
      "dial_code": "+359",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "BGN",
      "currency_name": "Bulgarian lev",
      "symbol": "лв",
    },
    {
      "name": "Burkina Faso",
      "flag": "🇧🇫",
      "code": "BF",
      "dial_code": "+226",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "XOF",
      "currency_name": "West African CFA franc",
      "symbol": "CFA",
    },
    {
      "name": "Burundi",
      "flag": "🇧🇮",
      "code": "BI",
      "dial_code": "+257",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "BIF",
      "currency_name": "Burundian franc",
      "symbol": "FBu",
    },
    {
      "name": "Cambodia",
      "flag": "🇰🇭",
      "code": "KH",
      "dial_code": "+855",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "KHR",
      "currency_name": "Cambodian riel",
      "symbol": "៛",
    },
    {
      "name": "Cameroon",
      "flag": "🇨🇲",
      "code": "CM",
      "dial_code": "+237",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "XAF",
      "currency_name": "Central African CFA franc",
      "symbol": "FCFA",
    },
    {
      "name": "Campione d'Italia",
      "flag": "🇮🇹",
      "code": "IT",
      "dial_code": "41",
      "min_length": 13,
      "max_length": 13,
      "currency_code": "CHF",
      "currency_name": "Swiss franc",
      "symbol": "CHF",
    },
    {
      "name": "Canada",
      "flag": "🇨🇦",
      "code": "CA",
      "dial_code": "+1",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "CAD",
      "currency_name": "Canadian dollar",
      "symbol": "CAD\$",
    },
    {
      "name": "Cape Verde",
      "flag": "🇨🇻",
      "code": "CV",
      "dial_code": "+238",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "CVE",
      "currency_name": "Cape Verdean escudo",
      "symbol": "\$",
    },
    {
      "name": "Cayman Islands",
      "flag": "🇰🇾",
      "code": "KY",
      "dial_code": "+345",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "KYD",
      "currency_name": "Cayman Islands dollar",
      "symbol": "\$",
    },
    {
      "name": "Central African Republic",
      "flag": "🇨🇫",
      "code": "CF",
      "dial_code": "+236",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "XAF",
      "currency_name": "Central African CFA franc",
      "symbol": "FCFA",
    },
    {
      "name": "Chad",
      "flag": "🇹🇩",
      "code": "TD",
      "dial_code": "+235",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "XAF",
      "currency_name": "Central African CFA franc",
      "symbol": "FCFA",
    },
    {
      "name": "Chile",
      "flag": "🇨🇱",
      "code": "CL",
      "dial_code": "+56",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "CLP",
      "currency_name": "Chilean peso",
      "symbol": "\$",
    },
    {
      "name": "China",
      "flag": "🇨🇳",
      "code": "CN",
      "dial_code": "+86",
      "min_length": 12,
      "max_length": 12,
      "currency_code": "CNY",
      "currency_name": "Chinese yuan",
      "symbol": "¥",
    },
    {
      "name": "Christmas Island",
      "flag": "🇨🇽",
      "code": "CX",
      "dial_code": "+61",
      "min_length": 15,
      "max_length": 15,
      "currency_code": "AUD",
      "currency_name": "Australian dollar",
      "symbol": "A\$",
    },
    {
      "name": "Cocos (Keeling) Islands",
      "flag": "🇨🇨",
      "code": "CC",
      "dial_code": "+61",
      "min_length": 15,
      "max_length": 15,
      "currency_code": "AUD",
      "currency_name": "Australian dollar",
      "symbol": "A\$",
    },
    {
      "name": "Colombia",
      "flag": "🇨🇴",
      "code": "CO",
      "dial_code": "+57",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "COP",
      "currency_name": "Colombian peso",
      "symbol": "\$",
    },
    {
      "name": "Comoros",
      "flag": "🇰🇲",
      "code": "KM",
      "dial_code": "+269",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "KMF",
      "currency_name": "Comorian franc",
      "symbol": "CF",
    },
    {
      "name": "Congo",
      "flag": "🇨🇬",
      "code": "CG",
      "dial_code": "+242",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "XAF",
      "currency_name": "Central African CFA franc",
      "symbol": "FCFA",
    },
    {
      "name": "Congo, The Democratic Republic of the Congo",
      "flag": "🇨🇩",
      "code": "CD",
      "dial_code": "+243",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "CDF",
      "currency_name": "Congolese franc",
      "symbol": "FC",
    },
    {
      "name": "Cook Islands",
      "flag": "🇨🇰",
      "code": "CK",
      "dial_code": "+682",
      "min_length": 5,
      "max_length": 5,
      "currency_code": "NZD",
      "currency_name": "New Zealand dollar",
      "symbol": "NZ\$",
    },
    {
      "name": "Costa Rica",
      "flag": "🇨🇷",
      "code": "CR",
      "dial_code": "+506",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "CRC",
      "currency_name": "Costa Rican colón",
      "symbol": "₡",
    },
    {
      "name": "Cote d'Ivoire",
      "flag": "🇨🇮",
      "code": "CI",
      "dial_code": "+225",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "XOF",
      "currency_name": "West African CFA franc",
      "symbol": "CFA",
    },
    {
      "name": "Croatia",
      "flag": "🇭🇷",
      "code": "HR",
      "dial_code": "+385",
      "min_length": 12,
      "max_length": 12,
      "currency_code": "HRK",
      "currency_name": "Croatian kuna",
      "symbol": "kn",
    },
    {
      "name": "Cuba",
      "flag": "🇨🇺",
      "code": "CU",
      "dial_code": "+53",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "CUC",
      "currency_name": "Cuban convertible peso",
      "symbol": "\$",
    },
    {
      "name": "Curaçao",
      "flag": "🇨🇼",
      "code": "CW",
      "dial_code": "+599",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "ANG",
      "currency_name": "Netherlands Antillean guilder",
      "symbol": "ƒ",
    },
    {
      "name": "Cyprus",
      "flag": "🇨🇾",
      "code": "CY",
      "dial_code": "+357",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Czech Republic",
      "flag": "🇨🇿",
      "code": "CZ",
      "dial_code": "+420",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "CZK",
      "currency_name": "Czech koruna",
      "symbol": "Kč",
    },
    {
      "name": "Denmark",
      "flag": "🇩🇰",
      "code": "DK",
      "dial_code": "+45",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "DKK",
      "currency_name": "Danish krone",
      "symbol": "kr",
    },
    {
      "name": "Djibouti",
      "flag": "🇩🇯",
      "code": "DJ",
      "dial_code": "+253",
      "min_length": 6,
      "max_length": 6,
      "currency_code": "DJF",
      "currency_name": "Djiboutian franc",
      "symbol": "Fdj",
    },
    {
      "name": "Dominica",
      "flag": "🇩🇲",
      "code": "DM",
      "dial_code": "+1767",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "XCD",
      "currency_name": "East Caribbean dollar",
      "symbol": "\$",
    },
    {
      "name": "Dominican Republic",
      "flag": "🇩🇴",
      "code": "DO",
      "dial_code": "+1849",
      "min_length": 12,
      "max_length": 12,
      "currency_code": "DOP",
      "currency_name": "Dominican peso",
      "symbol": "RD\$",
    },
    {
      "name": "Ecuador",
      "flag": "🇪🇨",
      "code": "EC",
      "dial_code": "+593",
      "min_length": 8,
      "max_length": 9,
      "currency_code": "USD",
      "currency_name": "United States dollar",
      "symbol": "\$",
    },
    {
      "name": "Egypt",
      "flag": "🇪🇬",
      "code": "EG",
      "dial_code": "+20",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "EGP",
      "currency_name": "Egyptian pound",
      "symbol": "£",
    },
    {
      "name": "El Salvador",
      "flag": "🇸🇻",
      "code": "SV",
      "dial_code": "+503",
      "min_length": 11,
      "max_length": 11,
      "currency_code": "SVC",
      "currency_name": "El Salvador Colon",
      "symbol": "\$",
    },
    {
      "name": "Equatorial Guinea",
      "flag": "🇬🇶",
      "code": "GQ",
      "dial_code": "+240",
      "min_length": 6,
      "max_length": 6,
      "currency_code": "XAF",
      "currency_name": "Central African CFA franc",
      "symbol": "FCFA",
    },
    {
      "name": "Eritrea",
      "flag": "🇪🇷",
      "code": "ER",
      "dial_code": "+291",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "ERN",
      "currency_name": "Eritrean nakfa",
      "symbol": "ናቕፋ",
    },
    {
      "name": "Estonia",
      "flag": "🇪🇪",
      "code": "EE",
      "dial_code": "+372",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Ethiopia",
      "flag": "🇪🇹",
      "code": "ET",
      "dial_code": "+251",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "ETB",
      "currency_name": "Ethiopian birr",
      "symbol": "Br",
    },
    {
      "name": "Falkland Islands (Malvinas)",
      "flag": "🇫🇰",
      "code": "FK",
      "dial_code": "+500",
      "min_length": 5,
      "max_length": 5,
      "currency_code": "FKP",
      "currency_name": "Falkland Islands pound",
      "symbol": "£",
    },
    {
      "name": "Faroe Islands",
      "flag": "🇫🇴",
      "code": "FO",
      "dial_code": "+298",
      "min_length": 6,
      "max_length": 6,
      "currency_code": "DKK",
      "currency_name": "Danish krone",
      "symbol": "kr",
    },
    {
      "name": "Fiji",
      "flag": "🇫🇯",
      "code": "FJ",
      "dial_code": "+679",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "FJD",
      "currency_name": "Fijian dollar",
      "symbol": "\$",
    },
    {
      "name": "Finland",
      "flag": "🇫🇮",
      "code": "FI",
      "dial_code": "+358",
      "min_length": 12,
      "max_length": 12,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "France",
      "flag": "🇫🇷",
      "code": "FR",
      "dial_code": "+33",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "French Guiana",
      "flag": "🇬🇫",
      "code": "GF",
      "dial_code": "+594",
      "min_length": 15,
      "max_length": 15,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "French Polynesia",
      "flag": "🇵🇫",
      "code": "PF",
      "dial_code": "+689",
      "min_length": 6,
      "max_length": 6,
      "currency_code": "XPF",
      "currency_name": "CFP franc",
      "symbol": "CFP",
    },
    {
      "name": "French Southern Territories",
      "flag": "🇹🇫",
      "code": "TF",
      "dial_code": "+262",
      "min_length": 15,
      "max_length": 15,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Gabon",
      "flag": "🇬🇦",
      "code": "GA",
      "dial_code": "+241",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "XAF",
      "currency_name": "Central African CFA franc",
      "symbol": "FCFA",
    },
    {
      "name": "Gambia",
      "flag": "🇬🇲",
      "code": "GM",
      "dial_code": "+220",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "GMD",
      "currency_name": "Gambian dalasi",
      "symbol": "D",
    },
    {
      "name": "Georgia",
      "flag": "🇬🇪",
      "code": "GE",
      "dial_code": "+995",
      "min_length": 8,
      "max_length": 9,
      "currency_code": "GEL",
      "currency_name": "Georgian Lari",
      "symbol": "₾",
    },
    {
      "name": "Germany",
      "flag": "🇩🇪",
      "code": "DE",
      "dial_code": "+49",
      "min_length": 9,
      "max_length": 13,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Ghana",
      "flag": "🇬🇭",
      "code": "GH",
      "dial_code": "+233",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "GHS",
      "currency_name": "Ghanaian cedi",
      "symbol": "₵",
    },
    {
      "name": "Gibraltar",
      "flag": "🇬🇮",
      "code": "GI",
      "dial_code": "+350",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "GIP",
      "currency_name": "Gibraltar pound",
      "symbol": "£",
    },
    {
      "name": "Greece",
      "flag": "🇬🇷",
      "code": "GR",
      "dial_code": "+30",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Greenland",
      "flag": "🇬🇱",
      "code": "GL",
      "dial_code": "+299",
      "min_length": 6,
      "max_length": 6,
      "currency_code": "DKK",
      "currency_name": "Danish krone",
      "symbol": "kr",
    },
    {
      "name": "Grenada",
      "flag": "🇬🇩",
      "code": "GD",
      "dial_code": "+1473",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "XCD",
      "currency_name": "East Caribbean dollar",
      "symbol": "\$",
    },
    {
      "name": "Guadeloupe",
      "flag": "🇬🇵",
      "code": "GP",
      "dial_code": "+590",
      "min_length": 15,
      "max_length": 15,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Guam",
      "flag": "🇬🇺",
      "code": "GU",
      "dial_code": "+1671",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "USD",
      "currency_name": "United States dollar",
      "symbol": "\$",
    },
    {
      "name": "Guatemala",
      "flag": "🇬🇹",
      "code": "GT",
      "dial_code": "+502",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "GTQ",
      "currency_name": "Guatemalan quetzal",
      "symbol": "Q",
    },
    {
      "name": "Guernsey",
      "flag": "🇬🇬",
      "code": "GG",
      "dial_code": "+44",
      "min_length": 6,
      "max_length": 6,
      "currency_code": "GBP",
      "currency_name": "British pound",
      "symbol": "£",
    },
    {
      "name": "Guinea",
      "flag": "🇬🇳",
      "code": "GN",
      "dial_code": "+224",
      "min_length": 8,
      "max_length": 9,
      "currency_code": "GNF",
      "currency_name": "Guinean franc",
      "symbol": "FG",
    },
    {
      "name": "Guinea-Bissau",
      "flag": "🇬🇼",
      "code": "GW",
      "dial_code": "+245",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "XOF",
      "currency_name": "West African CFA franc",
      "symbol": "CFA",
    },
    {
      "name": "Guyana",
      "flag": "🇬🇾",
      "code": "GY",
      "dial_code": "+592",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "GYD",
      "currency_name": "Guyanese dollar",
      "symbol": "\$",
    },
    {
      "name": "Haiti",
      "flag": "🇭🇹",
      "code": "HT",
      "dial_code": "+509",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "HTG",
      "currency_name": "Haitian gourde",
      "symbol": "G",
    },
    {
      "name": "Heard Island and Mcdonald Islands",
      "flag": "🇭🇲",
      "code": "HM",
      "dial_code": "+672",
      "min_length": 15,
      "max_length": 15,
      "currency_code": "AUD",
      "currency_name": "Australian dollar",
      "symbol": "A\$",
    },
    {
      "name": "Holy See (Vatican City State)",
      "flag": "🇻🇦",
      "code": "VA",
      "dial_code": "+379",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Honduras",
      "flag": "🇭🇳",
      "code": "HN",
      "dial_code": "+504",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "HNL",
      "currency_name": "Honduran lempira",
      "symbol": "L",
    },
    {
      "name": "Hong Kong",
      "flag": "🇭🇰",
      "code": "HK",
      "dial_code": "+852",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "HKD",
      "currency_name": "Hong Kong dollar",
      "symbol": "HK\$",
    },
    {
      "name": "Hungary",
      "flag": "🇭🇺",
      "code": "HU",
      "dial_code": "+36",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "HUF",
      "currency_name": "Hungarian forint",
      "symbol": "Ft",
    },
    {
      "name": "Iceland",
      "flag": "🇮🇸",
      "code": "IS",
      "dial_code": "+354",
      "min_length": 7,
      "max_length": 9,
      "currency_code": "ISK",
      "currency_name": "Icelandic króna",
      "symbol": "kr",
    },
    {
      "name": "India",
      "flag": "🇮🇳",
      "code": "IN",
      "dial_code": "+91",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "INR",
      "currency_name": "Indian rupee",
      "symbol": "₹",
    },
    {
      "name": "Indonesia",
      "flag": "🇮🇩",
      "code": "ID",
      "dial_code": "+62",
      "min_length": 10,
      "max_length": 13,
      "currency_code": "IDR",
      "currency_name": "Indonesian rupiah",
      "symbol": "Rp",
    },
    {
      "name": "Iran, Islamic Republic of Persian Gulf",
      "flag": "🇮🇷",
      "code": "IR",
      "dial_code": "+98",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "IRR",
      "currency_name": "Iranian rial",
      "symbol": "﷼"
    },
    {
      "name": "Iraq",
      "flag": "🇮🇶",
      "code": "IQ",
      "dial_code": "+964",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "IQD",
      "currency_name": "Iraqi dinar",
      "symbol": "ع.د",
    },
    {
      "name": "Ireland",
      "flag": "🇮🇪",
      "code": "IE",
      "dial_code": "+353",
      "min_length": 7,
      "max_length": 9,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Isle of Man",
      "flag": "🇮🇲",
      "code": "IM",
      "dial_code": "+44",
      "min_length": 6,
      "max_length": 6,
      "currency_code": "GBP",
      "currency_name": "British pound",
      "symbol": "£",
    },
    {
      "name": "Israel",
      "flag": "🇮🇱",
      "code": "IL",
      "dial_code": "+972",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "ILS",
      "currency_name": "Israeli new shekel",
      "symbol": "₪",
    },
    {
      "name": "Italy",
      "flag": "🇮🇹",
      "code": "IT",
      "dial_code": "+39",
      "min_length": 12,
      "max_length": 13,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Jamaica",
      "flag": "🇯🇲",
      "code": "JM",
      "dial_code": "+1876",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "JMD",
      "currency_name": "Jamaican dollar",
      "symbol": "J\$",
    },
    {
      "name": "Japan",
      "flag": "🇯🇵",
      "code": "JP",
      "dial_code": "+81",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "JPY",
      "currency_name": "Japanese yen",
      "symbol": "¥",
    },
    {
      "name": "Jersey",
      "flag": "🇯🇪",
      "code": "JE",
      "dial_code": "+44",
      "min_length": 6,
      "max_length": 6,
      "currency_code": "GBP",
      "currency_name": "British pound",
      "symbol": "£",
    },
    {
      "name": "Jordan",
      "flag": "🇯🇴",
      "code": "JO",
      "dial_code": "+962",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "JOD",
      "currency_name": "Jordanian dinar",
      "symbol": "د.ا",
    },
    {
      "name": "Kazakhstan",
      "flag": "🇰🇿",
      "code": "KZ",
      "dial_code": "+7",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "KZT",
      "currency_name": "Kazakhstani tenge",
      "symbol": "〒",
    },
    {
      "name": "Kenya",
      "flag": "🇰🇪",
      "code": "KE",
      "dial_code": "+254",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "KES",
      "currency_name": "Kenyan shilling",
      "symbol": "KSh",
    },
    {
      "name": "Kiribati",
      "flag": "🇰🇮",
      "code": "KI",
      "dial_code": "+686",
      "min_length": 5,
      "max_length": 5,
      "currency_code": "AUD",
      "currency_name": "Australian dollar",
      "symbol": "A\$",
    },
    {
      "name": "Korea, Democratic People's Republic of Korea",
      "flag": "🇰🇵",
      "code": "KP",
      "dial_code": "+850",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "KPW",
      "currency_name": "North Korean won",
      "symbol": "₩",
    },
    {
      "name": "Korea, Republic of South Korea",
      "flag": "🇰🇷",
      "code": "KR",
      "dial_code": "+82",
      "min_length": 11,
      "max_length": 11,
      "currency_code": "KRW",
      "currency_name": "South Korean won",
      "symbol": "₩",
    },
    {
      "name": "Kosovo",
      "flag": "🇽🇰",
      "code": "XK",
      "dial_code": "+383",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Kuwait",
      "flag": "🇰🇼",
      "code": "KW",
      "dial_code": "+965",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "KWD",
      "currency_name": "Kuwaiti dinar",
      "symbol": "د.ك",
    },
    {
      "name": "Kyrgyzstan",
      "flag": "🇰🇬",
      "code": "KG",
      "dial_code": "+996",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "KGS",
      "currency_name": "Kyrgyzstani som",
      "symbol": "с",
    },
    {
      "name": "Laos",
      "flag": "🇱🇦",
      "code": "LA",
      "dial_code": "+856",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "LAK",
      "currency_name": "Lao kip",
      "symbol": "₭",
    },
    {
      "name": "Latvia",
      "flag": "🇱🇻",
      "code": "LV",
      "dial_code": "+371",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Lebanon",
      "flag": "🇱🇧",
      "code": "LB",
      "dial_code": "+961",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "LBP",
      "currency_name": "Lebanese pound",
      "symbol": "£",
    },
    {
      "name": "Lesotho",
      "flag": "🇱🇸",
      "code": "LS",
      "dial_code": "+266",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "LSL",
      "currency_name": "Lesotho loti",
      "symbol": "L",
    },
    {
      "name": "Liberia",
      "flag": "🇱🇷",
      "code": "LR",
      "dial_code": "+231",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "LRD",
      "currency_name": "Liberian dollar",
      "symbol": "\$",
    },
    {
      "name": "Libyan Arab Jamahiriya",
      "flag": "🇱🇾",
      "code": "LY",
      "dial_code": "+218",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "LYD",
      "currency_name": "Libyan dinar",
      "symbol": "ل.د",
    },
    {
      "name": "Liechtenstein",
      "flag": "🇱🇮",
      "code": "LI",
      "dial_code": "+423",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "CHF",
      "currency_name": "Swiss franc",
      "symbol": "CHF",
    },
    {
      "name": "Lithuania",
      "flag": "🇱🇹",
      "code": "LT",
      "dial_code": "+370",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Luxembourg",
      "flag": "🇱🇺",
      "code": "LU",
      "dial_code": "+352",
      "min_length": 11,
      "max_length": 11,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Macao",
      "flag": "🇲🇴",
      "code": "MO",
      "dial_code": "+853",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "MOP",
      "currency_name": "Macanese pataca",
      "symbol": "MOP\$",
    },
    {
      "name": "Macedonia",
      "flag": "🇲🇰",
      "code": "MK",
      "dial_code": "+389",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "MKD",
      "currency_name": "Macedonian denar",
      "symbol": "ден",
    },
    {
      "name": "Madagascar",
      "flag": "🇲🇬",
      "code": "MG",
      "dial_code": "+261",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "MGA",
      "currency_name": "Malagasy ariary",
      "symbol": "Ar",
    },
    {
      "name": "Malawi",
      "flag": "🇲🇼",
      "code": "MW",
      "dial_code": "+265",
      "min_length": 7,
      "max_length": 9,
      "currency_code": "MWK",
      "currency_name": "Malawian kwacha",
      "symbol": "MK",
    },
    {
      "name": "Malaysia",
      "flag": "🇲🇾",
      "code": "MY",
      "dial_code": "+60",
      "min_length": 11,
      "max_length": 11,
      "currency_code": "MYR",
      "currency_name": "Malaysian ringgit",
      "symbol": "RM",
    },
    {
      "name": "Maldives",
      "flag": "🇲🇻",
      "code": "MV",
      "dial_code": "+960",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "MVR",
      "currency_name": "Maldivian rufiyaa",
      "symbol": ".ރ",
    },
    {
      "name": "Mali",
      "flag": "🇲🇱",
      "code": "ML",
      "dial_code": "+223",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "XOF",
      "currency_name": "West African CFA franc",
      "symbol": "CFA",
    },
    {
      "name": "Malta",
      "flag": "🇲🇹",
      "code": "MT",
      "dial_code": "+356",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Marshall Islands",
      "flag": "🇲🇭",
      "code": "MH",
      "dial_code": "+692",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "USD",
      "currency_name": "United States dollar",
      "symbol": "\$",
    },
    {
      "name": "Martinique",
      "flag": "🇲🇶",
      "code": "MQ",
      "dial_code": "+596",
      "min_length": 15,
      "max_length": 15,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Mauritania",
      "flag": "🇲🇷",
      "code": "MR",
      "dial_code": "+222",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "MRO",
      "currency_name": "Mauritanian ouguiya",
      "symbol": "UM",
    },
    {
      "name": "Mauritius",
      "flag": "🇲🇺",
      "code": "MU",
      "dial_code": "+230",
      "min_length": 7,
      "max_length": 8,
      "currency_code": "MUR",
      "currency_name": "Mauritian rupee",
      "symbol": "₨",
    },
    {
      "name": "Mayotte",
      "flag": "🇾🇹",
      "code": "YT",
      "dial_code": "+262",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Mexico",
      "flag": "🇲🇽",
      "code": "MX",
      "dial_code": "+52",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "MXN",
      "currency_name": "Mexican peso",
      "symbol": "\$",
    },
    {
      "name": "Micronesia, Federated States of Micronesia",
      "flag": "🇫🇲",
      "code": "FM",
      "dial_code": "+691",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "USD",
      "currency_name": "United States Dollar",
      "symbol": "\$",
    },
    {
      "name": "Moldova",
      "flag": "🇲🇩",
      "code": "MD",
      "dial_code": "+373",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "MDL",
      "currency_name": "Moldovan leu",
      "symbol": "L",
    },
    {
      "name": "Monaco",
      "flag": "🇲🇨",
      "code": "MC",
      "dial_code": "+377",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Mongolia",
      "flag": "🇲🇳",
      "code": "MN",
      "dial_code": "+976",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "MNT",
      "currency_name": "Mongolian tögrög",
      "symbol": "₮",
    },
    {
      "name": "Montenegro",
      "flag": "🇲🇪",
      "code": "ME",
      "dial_code": "+382",
      "min_length": 12,
      "max_length": 12,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Montserrat",
      "flag": "🇲🇸",
      "code": "MS",
      "dial_code": "+1664",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "XCD",
      "currency_name": "East Caribbean dollar",
      "symbol": "\$",
    },
    {
      "name": "Morocco",
      "flag": "🇲🇦",
      "code": "MA",
      "dial_code": "+212",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "MAD",
      "currency_name": "Moroccan dirham",
      "symbol": "MAD",
    },
    {
      "name": "Mozambique",
      "flag": "🇲🇿",
      "code": "MZ",
      "dial_code": "+258",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "MZN",
      "currency_name": "Mozambican metical",
      "symbol": "MT",
    },
    {
      "name": "Myanmar",
      "flag": "🇲🇲",
      "code": "MM",
      "dial_code": "+95",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "MMK",
      "currency_name": "Burmese kyat",
      "symbol": "Ks",
    },
    {
      "name": "Namibia",
      "flag": "🇳🇦",
      "code": "NA",
      "dial_code": "+264",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "NAD",
      "currency_name": "Namibian dollar",
      "symbol": "\$",
    },
    {
      "name": "Nauru",
      "flag": "🇳🇷",
      "code": "NR",
      "dial_code": "+674",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "AUD",
      "currency_name": "Australian dollar",
      "symbol": "A\$",
    },
    {
      "name": "Nepal",
      "flag": "🇳🇵",
      "code": "NP",
      "dial_code": "+977",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "NPR",
      "currency_name": "Nepalese rupee",
      "symbol": "₨",
    },
    {
      "name": "Netherlands",
      "flag": "🇳🇱",
      "code": "NL",
      "dial_code": "+31",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Netherlands Antilles",
      "flag": "",
      "code": "AN",
      "dial_code": "+599",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "ANG",
      "currency_name": "Netherlands Antillean guilder",
      "symbol": "ƒ",
    },
    {
      "name": "New Caledonia",
      "flag": "🇳🇨",
      "code": "NC",
      "dial_code": "+687",
      "min_length": 6,
      "max_length": 6,
      "currency_code": "XPF",
      "currency_name": "CFP franc",
      "symbol": "CFP",
    },
    {
      "name": "New Zealand",
      "flag": "🇳🇿",
      "code": "NZ",
      "dial_code": "+64",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "NZD",
      "currency_name": "New Zealand dollar",
      "symbol": "NZ\$",
    },
    {
      "name": "Nicaragua",
      "flag": "🇳🇮",
      "code": "NI",
      "dial_code": "+505",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "NIO",
      "currency_name": "Nicaraguan córdoba",
      "symbol": "C\$",
    },
    {
      "name": "Niger",
      "flag": "🇳🇪",
      "code": "NE",
      "dial_code": "+227",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "XOF",
      "currency_name": "West African CFA franc",
      "symbol": "CFA",
    },
    {
      "name": "Nigeria",
      "flag": "🇳🇬",
      "code": "NG",
      "dial_code": "+234",
      "min_length": 10,
      "max_length": 11,
      "currency_code": "NGN",
      "currency_name": "Nigerian naira",
      "symbol": "₦",
    },
    {
      "name": "Niue",
      "flag": "🇳🇺",
      "code": "NU",
      "dial_code": "+683",
      "min_length": 4,
      "max_length": 4,
      "currency_code": "NZD",
      "currency_name": "New Zealand dollar",
      "symbol": "NZ\$",
    },
    {
      "name": "Norfolk Island",
      "flag": "🇳🇫",
      "code": "NF",
      "dial_code": "+672",
      "min_length": 15,
      "max_length": 15,
      "currency_code": "AUD",
      "currency_name": "Australian dollar",
      "symbol": "A\$",
    },
    {
      "name": "Northern Mariana Islands",
      "flag": "🇲🇵",
      "code": "MP",
      "dial_code": "+1670",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "USD",
      "currency_name": "United States dollar",
      "symbol": "\$",
    },
    {
      "name": "Norway",
      "flag": "🇳🇴",
      "code": "NO",
      "dial_code": "+47",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "NOK",
      "currency_name": "Norwegian krone",
      "symbol": "kr",
    },
    {
      "name": "Oman",
      "flag": "🇴🇲",
      "code": "OM",
      "dial_code": "+968",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "OMR",
      "currency_name": "Omani rial",
      "symbol": "﷼",
    },
    {
      "name": "Pakistan",
      "flag": "🇵🇰",
      "code": "PK",
      "dial_code": "+92",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "PKR",
      "currency_name": "Pakistani rupee",
      "symbol": "₨",
    },
    {
      "name": "Palau",
      "flag": "🇵🇼",
      "code": "PW",
      "dial_code": "+680",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "USD",
      "currency_name": "United States dollar",
      "symbol": "\$",
    },
    {
      "name": "Palestine, State of",
      "flag": "🇵🇸",
      "code": "PS",
      "dial_code": "+970",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "ILS",
      "currency_name": "Israeli new sheqel",
      "symbol": "₪",
    },
    {
      "name": "Panama",
      "flag": "🇵🇦",
      "code": "PA",
      "dial_code": "+507",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "PAB",
      "currency_name": "Panamanian balboa",
      "symbol": "B/.",
    },
    {
      "name": "Papua New Guinea",
      "flag": "🇵🇬",
      "code": "PG",
      "dial_code": "+675",
      "min_length": 11,
      "max_length": 11,
      "currency_code": "PGK",
      "currency_name": "Papua New Guinean kina",
      "symbol": "K",
    },
    {
      "name": "Paraguay",
      "flag": "🇵🇾",
      "code": "PY",
      "dial_code": "+595",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "PYG",
      "currency_name": "Paraguayan guaraní",
      "symbol": "₲",
    },
    {
      "name": "Peru",
      "flag": "🇵🇪",
      "code": "PE",
      "dial_code": "+51",
      "min_length": 11,
      "max_length": 11,
      "currency_code": "PEN",
      "currency_name": "Peruvian sol",
      "symbol": "S/.",
    },
    {
      "name": "Philippines",
      "flag": "🇵🇭",
      "code": "PH",
      "dial_code": "+63",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "PHP",
      "currency_name": "Philippine peso",
      "symbol": "₱",
    },
    {
      "name": "Pitcairn",
      "flag": "🇵🇳",
      "code": "PN",
      "dial_code": "+64",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "NZD",
      "currency_name": "New Zealand dollar",
      "symbol": "NZ\$",
    },
    {
      "name": "Poland",
      "flag": "🇵🇱",
      "code": "PL",
      "dial_code": "+48",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "PLN",
      "currency_name": "Polish złoty",
      "symbol": "zł",
    },
    {
      "name": "Portugal",
      "flag": "🇵🇹",
      "code": "PT",
      "dial_code": "+351",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Puerto Rico",
      "flag": "🇵🇷",
      "code": "PR",
      "dial_code": "+1939",
      "min_length": 15,
      "max_length": 15,
      "currency_code": "USD",
      "currency_name": "United States dollar",
      "symbol": "\$",
    },
    {
      "name": "Qatar",
      "flag": "🇶🇦",
      "code": "QA",
      "dial_code": "+974",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "QAR",
      "currency_name": "Qatari riyal",
      "symbol": "﷼",
    },
    {
      "name": "Romania",
      "flag": "🇷🇴",
      "code": "RO",
      "dial_code": "+40",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "RON",
      "currency_name": "Romanian leu",
      "symbol": "L",
    },
    {
      "name": "Russia",
      "flag": "🇷🇺",
      "code": "RU",
      "dial_code": "+7",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "RUB",
      "currency_name": "Russian ruble",
      "symbol": "₽",
    },
    {
      "name": "Rwanda",
      "flag": "🇷🇼",
      "code": "RW",
      "dial_code": "+250",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "RWF",
      "currency_name": "Rwandan franc",
      "symbol": "FRw",
    },
    {
      "name": "Reunion",
      "flag": "🇷🇪",
      "code": "RE",
      "dial_code": "+262",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Saint Barthelemy",
      "flag": "🇧🇱",
      "code": "BL",
      "dial_code": "+590",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Saint Helena, Ascension and Tristan Da Cunha",
      "flag": "🇸🇭",
      "code": "SH",
      "dial_code": "+290",
      "min_length": 4,
      "max_length": 4,
      "currency_code": "SHP",
      "currency_name": "Saint Helena pound",
      "symbol": "£",
    },
    {
      "name": "Saint Kitts and Nevis",
      "flag": "🇰🇳",
      "code": "KN",
      "dial_code": "+1869",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "XCD",
      "currency_name": "East Caribbean dollar",
      "symbol": "\$",
    },
    {
      "name": "Saint Lucia",
      "flag": "🇱🇨",
      "code": "LC",
      "dial_code": "+1758",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "XCD",
      "currency_name": "East Caribbean dollar",
      "symbol": "\$",
    },
    {
      "name": "Saint Martin",
      "flag": "🇲🇫",
      "code": "MF",
      "dial_code": "+590",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Saint Pierre and Miquelon",
      "flag": "🇵🇲",
      "code": "PM",
      "dial_code": "+508",
      "min_length": 6,
      "max_length": 6,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Saint Vincent and the Grenadines",
      "flag": "🇻🇨",
      "code": "VC",
      "dial_code": "+1784",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "XCD",
      "currency_name": "East Caribbean dollar",
      "symbol": "\$",
    },
    {
      "name": "Samoa",
      "flag": "🇼🇸",
      "code": "WS",
      "dial_code": "+685",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "WST",
      "currency_name": "Samoan tālā",
      "symbol": "WS\$",
    },
    {
      "name": "San Marino",
      "flag": "🇸🇲",
      "code": "SM",
      "dial_code": "+378",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Sao Tome and Principe",
      "flag": "🇸🇹",
      "code": "ST",
      "dial_code": "+239",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "STD",
      "currency_name": "São Tomé and Príncipe dobra",
      "symbol": "Db",
    },
    {
      "name": "Saudi Arabia",
      "flag": "🇸🇦",
      "code": "SA",
      "dial_code": "+966",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "SAR",
      "currency_name": "Saudi riyal",
      "symbol": "﷼",
    },
    {
      "name": "Senegal",
      "flag": "🇸🇳",
      "code": "SN",
      "dial_code": "+221",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "XOF",
      "currency_name": "West African CFA franc",
      "symbol": "CFA",
    },
    {
      "name": "Serbia",
      "flag": "🇷🇸",
      "code": "RS",
      "dial_code": "+381",
      "min_length": 12,
      "max_length": 12,
      "currency_code": "RSD",
      "currency_name": "Serbian dinar",
      "symbol": "Дин.",
    },
    {
      "name": "Seychelles",
      "flag": "🇸🇨",
      "code": "SC",
      "dial_code": "+248",
      "min_length": 6,
      "max_length": 6,
      "currency_code": "SCR",
      "currency_name": "Seychellois rupee",
      "symbol": "₨",
    },
    {
      "name": "Sierra Leone",
      "flag": "🇸🇱",
      "code": "SL",
      "dial_code": "+232",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "SLL",
      "currency_name": "Sierra Leonean leone",
      "symbol": "Le",
    },
    {
      "name": "Singapore",
      "flag": "🇸🇬",
      "code": "SG",
      "dial_code": "+65",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "SGD",
      "currency_name": "Singapore dollar",
      "symbol": "S\$",
    },
    {
      "name": "Slovakia",
      "flag": "🇸🇰",
      "code": "SK",
      "dial_code": "+421",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Slovenia",
      "flag": "🇸🇮",
      "code": "SI",
      "dial_code": "+386",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Solomon Islands",
      "flag": "🇸🇧",
      "code": "SB",
      "dial_code": "+677",
      "min_length": 5,
      "max_length": 5,
      "currency_code": "SBD",
      "currency_name": "Solomon Islands dollar",
      "symbol": "\$",
    },
    {
      "name": "Somalia",
      "flag": "🇸🇴",
      "code": "SO",
      "dial_code": "+252",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "SOS",
      "currency_name": "Somali shilling",
      "symbol": "S",
    },
    {
      "name": "South Africa",
      "flag": "🇿🇦",
      "code": "ZA",
      "dial_code": "+27",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "ZAR",
      "currency_name": "South African rand",
      "symbol": "R",
    },
    {
      "name": "South Sudan",
      "flag": "🇸🇸",
      "code": "SS",
      "dial_code": "+211",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "SSP",
      "currency_name": "South Sudanese pound",
      "symbol": "£",
    },
    {
      "name": "South Georgia and the South Sandwich Islands",
      "flag": "🇬🇸",
      "code": "GS",
      "dial_code": "+500",
      "min_length": 15,
      "max_length": 15,
      "currency_code": "GBP",
      "currency_name": "British pound",
      "symbol": "£",
    },
    {
      "name": "Spain",
      "flag": "🇪🇸",
      "code": "ES",
      "dial_code": "+34",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "EUR",
      "currency_name": "Euro",
      "symbol": "€",
    },
    {
      "name": "Sri Lanka",
      "flag": "🇱🇰",
      "code": "LK",
      "dial_code": "+94",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "LKR",
      "currency_name": "Sri Lankan rupee",
      "symbol": "₨",
    },
    {
      "name": "Sudan",
      "flag": "🇸🇩",
      "code": "SD",
      "dial_code": "+249",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "SDG",
      "currency_name": "Sudanese pound",
      "symbol": "ج.س.",
    },
    {
      "name": "Suriname",
      "flag": "🇸🇷",
      "code": "SR",
      "dial_code": "+597",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "SRD",
      "currency_name": "Surinamese dollar",
      "symbol": "\$",
    },
    {
      "name": "Svalbard and Jan Mayen",
      "flag": "🇸🇯",
      "code": "SJ",
      "dial_code": "+47",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "NOK",
      "currency_name": "Norwegian krone",
      "symbol": "kr",
    },
    {
      "name": "Swaziland",
      "flag": "🇸🇿",
      "code": "SZ",
      "dial_code": "+268",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "SZL",
      "currency_name": "Swazi lilangeni",
      "symbol": "E",
    },
    {
      "name": "Sweden",
      "flag": "🇸🇪",
      "code": "SE",
      "dial_code": "+46",
      "min_length": 7,
      "max_length": 13,
      "currency_code": "SEK",
      "currency_name": "Swedish krona",
      "symbol": "kr",
    },
    {
      "name": "Switzerland",
      "flag": "🇨🇭",
      "code": "CH",
      "dial_code": "+41",
      "min_length": 12,
      "max_length": 12,
      "currency_code": "CHF",
      "currency_name": "Swiss franc",
      "symbol": "CHF",
    },
    {
      "name": "Syrian Arab Republic",
      "flag": "🇸🇾",
      "code": "SY",
      "dial_code": "+963",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "SYP",
      "currency_name": "Syrian pound",
      "symbol": "LS",
    },
    {
      "name": "Taiwan",
      "flag": "🇹🇼",
      "code": "TW",
      "dial_code": "+886",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "TWD",
      "currency_name": "New Taiwan dollar",
      "symbol": "NT\$",
    },
    {
      "name": "Tajikistan",
      "flag": "🇹🇯",
      "code": "TJ",
      "dial_code": "+992",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "TJS",
      "currency_name": "Tajikistani somoni",
      "symbol": "SM",
    },
    {
      "name": "Tanzania, United Republic of Tanzania",
      "flag": "🇹🇿",
      "code": "TZ",
      "dial_code": "+255",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "TZS",
      "currency_name": "Tanzanian shilling",
      "symbol": "TSh",
    },
    {
      "name": "Thailand",
      "flag": "🇹🇭",
      "code": "TH",
      "dial_code": "+66",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "THB",
      "currency_name": "Thai baht",
      "symbol": "฿",
    },
    {
      "name": "Timor-Leste",
      "flag": "🇹🇱",
      "code": "TL",
      "dial_code": "+670",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "USD",
      "currency_name": "United States dollar",
      "symbol": "\$",
    },
    {
      "name": "Togo",
      "flag": "🇹🇬",
      "code": "TG",
      "dial_code": "+228",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "XOF",
      "currency_name": "West African CFA franc",
      "symbol": "CFA",
    },
    {
      "name": "Tokelau",
      "flag": "🇹🇰",
      "code": "TK",
      "dial_code": "+690",
      "min_length": 4,
      "max_length": 4,
      "currency_code": "NZD",
      "currency_name": "New Zealand dollar",
      "symbol": "NZ\$",
    },
    {
      "name": "Tonga",
      "flag": "🇹🇴",
      "code": "TO",
      "dial_code": "+676",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "TOP",
      "currency_name": "Tongan paʻanga",
      "symbol": "T\$",
    },
    {
      "name": "Trinidad and Tobago",
      "flag": "🇹🇹",
      "code": "TT",
      "dial_code": "+1868",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "TTD",
      "currency_name": "Trinidad and Tobago dollar",
      "symbol": "TT\$",
    },
    {
      "name": "Tunisia",
      "flag": "🇹🇳",
      "code": "TN",
      "dial_code": "+216",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "TND",
      "currency_name": "Tunisian dinar",
      "symbol": "د.ت",
    },
    {
      "name": "Turkey",
      "flag": "🇹🇷",
      "code": "TR",
      "dial_code": "+90",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "TRY",
      "currency_name": "Turkish lira",
      "symbol": "₺",
    },
    {
      "name": "Turkmenistan",
      "flag": "🇹🇲",
      "code": "TM",
      "dial_code": "+993",
      "min_length": 8,
      "max_length": 8,
      "currency_code": "TMT",
      "currency_name": "Turkmenistan manat",
      "symbol": "m",
    },
    {
      "name": "Turks and Caicos Islands",
      "flag": "🇹🇨",
      "code": "TC",
      "dial_code": "+1649",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "USD",
      "currency_name": "United States dollar",
      "symbol": "\$",
    },
    {
      "name": "Tuvalu",
      "flag": "🇹🇻",
      "code": "TV",
      "dial_code": "+688",
      "min_length": 6,
      "max_length": 6,
      "currency_code": "AUD",
      "currency_name": "Australian dollar",
      "symbol": "A\$",
    },
    {
      "name": "Uganda",
      "flag": "🇺🇬",
      "code": "UG",
      "dial_code": "+256",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "UGX",
      "currency_name": "Ugandan shilling",
      "symbol": "USh",
    },
    {
      "name": "Ukraine",
      "flag": "🇺🇦",
      "code": "UA",
      "dial_code": "+380",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "UAH",
      "currency_name": "Ukrainian hryvnia",
      "symbol": "₴",
    },
    {
      "name": "United Arab Emirates",
      "flag": "🇦🇪",
      "code": "AE",
      "dial_code": "+971",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "AED",
      "currency_name": "United Arab Emirates dirham",
      "symbol": "د.إ",
    },
    {
      "name": "United Kingdom",
      "flag": "🇬🇧",
      "code": "GB",
      "dial_code": "+44",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "GBP",
      "currency_name": "British pound",
      "symbol": "£",
    },
    {
      "name": "United States",
      "flag": "🇺🇸",
      "code": "US",
      "dial_code": "+1",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "USD",
      "currency_name": "United States dollar",
      "symbol": "\$",
    },
    {
      "name": "Uruguay",
      "flag": "🇺🇾",
      "code": "UY",
      "dial_code": "+598",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "UYU",
      "currency_name": "Uruguayan peso",
      "symbol": "\$U",
    },
    {
      "name": "Uzbekistan",
      "flag": "🇺🇿",
      "code": "UZ",
      "dial_code": "+998",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "UZS",
      "currency_name": "Uzbekistani so'm",
      "symbol": "лв",
    },
    {
      "name": "Vanuatu",
      "flag": "🇻🇺",
      "code": "VU",
      "dial_code": "+678",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "VUV",
      "currency_name": "Vanuatu vatu",
      "symbol": "VT",
    },
    {
      "name": "Venezuela, Bolivarian Republic of Venezuela",
      "flag": "🇻🇪",
      "code": "VE",
      "dial_code": "+58",
      "min_length": 10,
      "max_length": 10,
      "currency_code": "VEF",
      "currency_name": "Venezuelan bolívar",
      "symbol": "Bs",
    },
    {
      "name": "Vietnam",
      "flag": "🇻🇳",
      "code": "VN",
      "dial_code": "+84",
      "min_length": 11,
      "max_length": 11,
      "currency_code": "VND",
      "currency_name": "Vietnamese đồng",
      "symbol": "₫",
    },
    {
      "name": "Virgin Islands, British",
      "flag": "🇻🇬",
      "code": "VG",
      "dial_code": "+1284",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "USD",
      "currency_name": "United States dollar",
      "symbol": "\$",
    },
    {
      "name": "Virgin Islands, U.S.",
      "flag": "🇻🇮",
      "code": "VI",
      "dial_code": "+1340",
      "min_length": 7,
      "max_length": 7,
      "currency_code": "USD",
      "currency_name": "United States dollar",
      "symbol": "\$",
    },
    {
      "name": "Wallis and Futuna",
      "flag": "🇼🇫",
      "code": "WF",
      "dial_code": "+681",
      "min_length": 6,
      "max_length": 6,
      "currency_code": "XPF",
      "currency_name": "CFP franc",
      "symbol": "CFP",
    },
    {
      "name": "Yemen",
      "flag": "🇾🇪",
      "code": "YE",
      "dial_code": "+967",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "YER",
      "currency_name": "Yemeni rial",
      "symbol": "﷼",
    },
    {
      "name": "Zambia",
      "flag": "🇿🇲",
      "code": "ZM",
      "dial_code": "+260",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "ZMW",
      "currency_name": "Zambian kwacha",
      "symbol": "ZK",
    },
    {
      "name": "Zimbabwe",
      "flag": "🇿🇼",
      "code": "ZW",
      "dial_code": "+263",
      "min_length": 9,
      "max_length": 9,
      "currency_code": "ZWL",
      "currency_name": "Zimababwe dollar",
      "symbol": "Z\$",
    }
  ];
}
